name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Clippy
      run: rustup component add clippy
    - name: Get Rustfmt
      run: rustup component add rustfmt
    - name: Get Rust Nightly
      run: rustup toolchain install nightly --allow-downgrade && rustup override set nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run lints
      run: cargo clippy --verbose && cargo fmt -- --check --verbose

